spring.application.name=APILoginManager

server.port=8082

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

###################PRODUCCION###################################
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/domaine_db
#
#spring.datasource.username=app_user
#spring.datasource.password=CICADA3301
################################################################

###################PRUEBAS EN LOCAL#############################
	spring.datasource.url=jdbc:mysql://localhost:3306/retoappbbc_db
	spring.datasource.username=root
	spring.datasource.password=mysql
################################################################

# URL de base del nginx para generar links en emails
app.base-url=http://localhost:8082

spring.jpa.generate-ddl=false

#En desarrollo y CI/CD= update, create arranque inicial o modificacion del schema
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#secret en Base64-384bits
#expiration en milisegundos (un mes)
jwt.secret=/sWwResFLrnjR1XEEMShseNxWVRUAgeiAdeKvCsZrwZ3LTzuQhdK4vD+jx5NyMId
jwt.expiration=3600000

#confirmacion del registro de usuario via mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saultdomainedesault@gmail.com
spring.mail.password=qdqkxkpuefmnrfrv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
